service: python-pdf-chat
frameworkVersion: '3'

provider:
  name: aws
  stage: dev
  region: us-east-1
  tracing:
    lambda: true
  httpApi:
    cors: true
    authorizers:
      cognitoAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: ${self:custom.issuerUrl}
        audience:
          - !Ref CognitoUserPoolClient
  layers:
    - arn:aws:lambda:us-east-1:017000801446:layer:AWSLambdaPowertoolsPythonV2-Arm64:51
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:ListBucket
          Resource: arn:aws:s3:::${self:custom.documentBucket}/*
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: !GetAtt DocumentTable.Arn
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: !GetAtt MemoryTable.Arn
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
          Resource: !GetAtt EmbeddingQueue.Arn
        - Effect: Allow
          Action:
            - bedrock:InvokeModel
          Resource: arn:aws:bedrock:*::foundation-model/amazon.titan-embed-text-v1
        - Effect: Allow
          Action:
            - bedrock:InvokeModel
          Resource:
            - arn:aws:bedrock:*::foundation-model/anthropic.claude-v2
            - arn:aws:bedrock:*::foundation-model/amazon.titan-embed-text-v1

package: 
  individually: true

custom:
  pythonRequirements:
    dockerizePip: true
  stackName: ${self:service}-${self:provider.stage}
  documentBucket: ${self:custom.stackName}-${self:provider.region}-${aws:accountId}
  cognitoUserPool: !Ref CognitoUserPool
  issuerUrl: 
    Fn::Sub: "https://cognito-idp.${self:provider.region}.amazonaws.com/${CognitoUserPool}"

functions:
  GeneratePresignedUrl:
    handler: src/generate_presigned_url/main.handler
    runtime: python3.11
    architecture: arm64
    timeout: 29
    environment:
      BUCKET: ${self:custom.documentBucket}
      REGION: ${self:provider.region}
    events:
      - httpApi:
          path: /generate_presigned_url
          method: get
          authorizer:
            name: cognitoAuthorizer

  UploadTrigger:
    handler: src/upload_trigger/main.handler
    runtime: python3.11
    architecture: arm64
    environment:
      DOCUMENT_TABLE: !Ref DocumentTable
      MEMORY_TABLE: !Ref MemoryTable
      QUEUE: !GetAtt EmbeddingQueue.QueueName
      BUCKET: ${self:custom.documentBucket}
    events:
      - s3:
          bucket: ${self:custom.documentBucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .pdf
          existing: true

  GetDocument:
    handler: src/get_document/main.handler
    runtime: python3.11
    architecture: arm64
    timeout: 29
    environment:
      DOCUMENT_TABLE: !Ref DocumentTable
      MEMORY_TABLE: !Ref MemoryTable
    events:
      - httpApi:
          path: /doc/{documentid}/{conversationId}
          method: get
          authorizer:
            name: cognitoAuthorizer

  GetAllDocuments:
    handler: src/get_all_documents/main.handler
    runtime: python3.11
    architecture: arm64
    timeout: 29
    environment:
      DOCUMENT_TABLE: !Ref DocumentTable
    events:
      - httpApi:
          path: /doc
          method: get
          authorizer:
            name: cognitoAuthorizer
  
  AddConversation:
    handler: src/add_conversation/main.handler
    runtime: python3.11
    architecture: arm64
    timeout: 29
    environment:
      DOCUMENT_TABLE: !Ref DocumentTable
      MEMORY_TABLE: !Ref MemoryTable
    events:
      - httpApi:
          path: /doc/{documentid}
          method: post
          authorizer:
            name: cognitoAuthorizer

  GenerateEmbeddings:
    handler: src/generate_embeddings/main.handler
    runtime: python3.11
    architecture: arm64
    timeout: 29
    environment:
      DOCUMENT_TABLE: !Ref DocumentTable
      BUCKET: ${self:custom.documentBucket}
    events:
      - sqs:
          arn: !GetAtt EmbeddingQueue.Arn
          batchSize: 1

  GenerateResponse:
    handler: src/generate_response/main.handler
    runtime: python3.11
    architecture: arm64
    timeout: 29
    environment:
      MEMORY_TABLE: !Ref MemoryTable
      BUCKET: ${self:custom.documentBucket}
    events:
      - httpApi:
          path: /{documentid}/{conversationid}
          method: post
          authorizer:
            name: cognitoAuthorizer

resources:
  Resources:
    DocumentBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: ${self:custom.documentBucket}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - HEAD
                - POST
                - DELETE
              AllowedOrigins:
                - "*"
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

    DocumentBucketPolicy:
      Type: "AWS::S3::BucketPolicy"
      Properties:
        PolicyDocument:
          Id: EnforceHttpsPolicy
          Version: "2012-10-17"
          Statement:
            - Sid: EnforceHttpsSid
              Effect: Deny
              Principal: "*"
              Action: "s3:*"
              Resource:
                - "arn:aws:s3:::${self:custom.documentBucket}/*"
                - "arn:aws:s3:::${self:custom.documentBucket}"
              Condition:
                Bool:
                  "aws:SecureTransport": "false"
        Bucket: ${self:custom.documentBucket}

    EmbeddingQueue:
      Type: AWS::SQS::Queue
      DeletionPolicy: Delete
      UpdateReplacePolicy: Delete
      Properties:
        VisibilityTimeout: 180
        MessageRetentionPeriod: 3600

    EmbeddingQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref EmbeddingQueue
        PolicyDocument:
          Version: "2012-10-17"
          Id: SecureTransportPolicy
          Statement:
            - Sid: AllowSecureTransportOnly
              Effect: Deny
              Principal: "*"
              Action: "SQS:*"
              Resource: "*"
              Condition:
                Bool:
                  aws:SecureTransport: false

    DocumentTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      UpdateReplacePolicy: Delete
      Properties:
        KeySchema:
          - AttributeName: userid
            KeyType: HASH
          - AttributeName: documentid
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: userid
            AttributeType: S
          - AttributeName: documentid
            AttributeType: S
        BillingMode: PAY_PER_REQUEST

    MemoryTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      UpdateReplacePolicy: Delete
      Properties:
        KeySchema:
          - AttributeName: SessionId
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: SessionId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      DeletionPolicy: Delete
      UpdateReplacePolicy: Delete
      Properties:
        AutoVerifiedAttributes:
          - email
        UsernameAttributes:
          - email
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: true
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId: !Ref CognitoUserPool
        ClientName: !Ref CognitoUserPool
        GenerateSecret: false

  Outputs:
    CognitoUserPool:
      Value: !Ref CognitoUserPool
    CognitoUserPoolClient:
      Value: !Ref CognitoUserPoolClient

plugins:
  - serverless-python-requirements
